name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    env:
      API_BASE_URL: http://127.0.0.1:3000
      API_USERS: http://127.0.0.1:3000/users
      API_OAUTH: http://127.0.0.1:3000/oauth
      API_CAMPAIGNS: http://127.0.0.1:3000/campaigns
      API_CHARACTERS: http://127.0.0.1:3000/characters
      API_DD5E: http://127.0.0.1:3000/dnd5e
      API_GOOGLE_YOUTUBE: http://127.0.0.1:3000/youtube
      API_GOOGLE_KEY: test-key
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Checking lint
        run:  npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run coverage:cy

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Cypress Tests**
            All cypress tests was runned with success !!
